### PR TITLE
phy mtu and data_length negotiations

### LINKED ISSUE #5: Data Length Extension negotiation
The BLE data length extension must be negotiated using `sd_ble_gap_data_length_update` and events `on_data_length_update_request`, `on_data_length_update`

Nordic's equivalent code is in `nrf_ble_gatt.c`

### LINKED ISSUE #6: ATT MTU negotiation
Similarly to #5, the ATT MTU must be negotiated using `sd_ble_gattc_exchange_mtu_request`. I think it's only necessary if we're the GATT client.

### PR DESCRIPTION
**Pull request by jacobrosenthal**
closes #5 and closes #6   (eventually)

Im using S140 7.0.1 peripheral state charts
https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.s140.api.v7.0.1/group___b_l_e___g_a_p___d_a_t_a___l_e_n_g_t_h___u_p_d_a_t_e___p_r_o_c_e_d_u_r_e___m_s_c.html

https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.s140.api.v7.0.1/group___b_l_e___g_a_p___p_e_r_i_p_h_e_r_a_l___p_h_y___u_p_d_a_t_e.html

My pixel enumerates the ble_bas_peripheral example with this code
```
0.000000 INFO  Hello World!
└─ ble_bas_peripheral::__cortex_m_rt_main @ examples/src/bin/ble_bas_peripheral.rs:159
0.000001 WARN  You're giving more RAM to the softdevice than needed. You can change your app's RAM start address to 536925320
└─ nrf_softdevice::softdevice::{{impl}}::enable @ nrf-softdevice/src/softdevice.rs:283
0.000002 INFO  hi
└─ nrf_softdevice::ble::gatt_server::register @ nrf-softdevice/src/ble/gatt_server.rs:57
0.000003 INFO  Advertising started!
└─ nrf_softdevice::ble::peripheral::advertise::{{closure}} @ nrf-softdevice/src/ble/peripheral.rs:160
0.000004 TRACE on_connected conn_handle=3
└─ nrf_softdevice::ble::events::on_connected @ nrf-softdevice/src/ble/events.rs:123
0.000005 TRACE conn 0: connected
└─ nrf_softdevice::ble::connection::{{impl}}::new @ nrf-softdevice/src/ble/connection.rs:212
0.000006 INFO  advertising done!
└─ ble_bas_peripheral::__static_executor_task_bluetooth_task::{{closure}} @ examples/src/bin/ble_bas_peripheral.rs:132
0.000007 TRACE on_data_length_update_request conn_handle=3 max_rx_octets=251 max_rx_time_us=2120 max_tx_octets=27 max_tx_time_us=328
└─ nrf_softdevice::ble::events::on_data_length_update_request @ nrf-softdevice/src/ble/events.rs:300
0.000008 TRACE on_data_length_update conn_handle=3 max_rx_octets=27 max_rx_time_us=328 max_tx_octets=132 max_tx_time_us=2120
└─ nrf_softdevice::ble::events::on_data_length_update @ nrf-softdevice/src/ble/events.rs:329
0.000009 TRACE on_phy_update_request conn_handle=3 rx_phys=3 tx_phys=3
└─ nrf_softdevice::ble::events::on_phy_update_request @ nrf-softdevice/src/ble/events.rs:254
0.000010 TRACE on_phy_update conn_handle=3 status=0 rx_phy=2 tx_phy=2
└─ nrf_softdevice::ble::events::on_phy_update @ nrf-softdevice/src/ble/events.rs:282
0.000011 TRACE on_conn_param_update conn_handle=3
└─ nrf_softdevice::ble::events::on_conn_param_update @ nrf-softdevice/src/ble/events.rs:157
0.000012 TRACE on_conn_param_update conn_handle=3
└─ nrf_softdevice::ble::events::on_conn_param_update @ nrf-softdevice/src/ble/events.rs:157
```

still have to do all the negotiation logic around what user provides and what peer requests etc.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Im not sure why it requested 3, which I thought I gave it, but then it ended up with 2?
```
└─ nrf_softdevice::ble::events::on_data_length_update @ nrf-softdevice/src/ble/events.rs:337
0.000009 TRACE on_phy_update_request conn_handle=3 rx_phys=3 tx_phys=3
└─ nrf_softdevice::ble::events::on_phy_update_request @ nrf-softdevice/src/ble/events.rs:260
0.000010 TRACE on_phy_update conn_handle=3 status=0 rx_phy=2 tx_phy=2
```

also with the new commit you can see the double negotiation of params im not sure whos requesting
```
└─ nrf_softdevice::ble::events::on_phy_update @ nrf-softdevice/src/ble/events.rs:288
0.000011 TRACE on_conn_param_update conn_handle=3 conn_sup_timeout=500 max_conn_interval=6 min_conn_interval=6 slave_latency=0
└─ nrf_softdevice::ble::events::on_conn_param_update @ nrf-softdevice/src/ble/events.rs:159
0.000012 TRACE on_conn_param_update conn_handle=3 conn_sup_timeout=500 max_conn_interval=36 min_conn_interval=36 slave_latency=0
└─ nrf_softdevice::ble::events::on_conn_param_update @ nrf-softdevice/src/ble/events.rs:159
```

**Comment by jacobrosenthal** [comment]
I Moved the params up to the fn call, ex:
(and also screwed up this commend like 3 times :) )

let conn_params = gap_evt.params.conn_param_update.conn_params;

instead passed directly to on_conn_param_update
pub(crate) unsafe fn on_conn_param_update(
_ble_evt: *const raw::ble_evt_t,
gap_evt: &raw::ble_gap_evt_t,
conn_params: &raw::ble_gap_conn_params_t

Do we even need the original ble_evts? theyre going largely unused.

**Review by Dirbaio — COMMENTED** [review]
Nice! Thanks a lot for taking a look.

Regarding passing the `params` structs from `on_evt` instead of getting them in the `on_data_length_update_request` & co funcs:
1. It must be a reference, not a copy. Some events contain "flexible arrays" which are "length 0" from Rust's PoV. If you copy, the flexarray won't be copied, and then using `get_flexarray` would be UB.
2. I'd like to either do it for all events or none at all, for consistency.
3. Many events just take the ble_evt raw pointer and pass it through the portal. The code at the other side gets the union members from it. If we do this in `on_evt` for all events, it'll be duplicate code for those. (You can't pass references through portals... I tried to make Portal work with arguments with lifetimes but failed. I'm not sure if it's possible.)

Given 2 and 3 I think it's better to unpack the unions in the individual event functions, not in `on_evt`.

**Comment by jacobrosenthal** [comment]
NP. Ill rip that commit off again.

**Comment by Dirbaio** [comment]
Looks great! Tested with my Pixel 3A, works!

> Im not sure why it requested 3, which I thought I gave it, but then it ended up with 2?

That's because it's a bitfield. 3 is `BLE_GAP_PHY_1MBPS | BLE_GAP_PHY_2MBPS`, and the softdevice ended up choosing `BLE_GAP_PHY_2MBPS` (2). I think it's normal.

**Comment by jacobrosenthal** [comment]
I brought in the concept of per connection state (gatt link) used in the sdk. 
But it still needs a method of filling it from the app main

They create a global here https://github.com/akiles/nrf5_sdk/blob/aa64d9218502933316e22c570b789b4a4c83de5b/examples/ble_peripheral/ble_app_eddystone/main.c#L78 and init it with data_length, att_mtu_desired_periph, and att_mtu_desired_central

Likewise this is how to handle #6 

This COULD be merged as is, it does work.

But it does add a ton of comments and todos so . up to you

**Comment by jacobrosenthal** [comment]
Oh also could still use user functions to set params as well as dry up some duplicated code

**Comment by jacobrosenthal** [comment]
We talked about doing portals instead of signals but that doesnt seem to help much. Instead I pulled the negotiotion back out of the handler to AFTER the signal, so I dont need to pass data in as well as back out. This means yet another copy of negotiation code in both peripheral and central but oh well.

Also we talked about sticking a config onto the softdevice config, but this config get passed to the softdevice enable, it gets passed to advertise or connect, so I made it a specific config for each of those. 

Note those two configs could probably be shared into a common struct because Im not sure there are any fields that central would want that peripheral wouldnt...

**Comment by jacobrosenthal** [comment]
Also this is brittle sadly.. and its repeated too.. 
```
        link.data_length_desired = config.data_length_desired;
        state.link.replace(link);

```

**Comment by jacobrosenthal** [comment]
Solved cell get and set with #![feature(cell_update)] since were on nightly anyway

**Comment by jacobrosenthal** [comment]
So the main architectural problem I currently dont know how to deal with is

 I can provide async user functions for like phy_update or mtu_update, and then its all well and good to await a rsp, and then I can even await those async fn inside of connect and advertise, because those are async..but something like  on_exchange_mtu_request handler isnt async so I cant await there to deal with something like BUSY response.. 

so how to spawn an mtu_exchange from within a on_evt handler

**Comment by Dirbaio** [comment]
Rebased, squashed and merged!

Sorry for taking so long, I've been sidetracked by non-bluetooth things for a few months but I'm back now.

Thanks a lot for working on this. I've decided to merge as-is as it works quite well already. I'll address a few loose ends the following days.

> I can provide async user functions for like phy_update or mtu_update, and then its all well and good to await a rsp, and then I can even await those async fn inside of connect and advertise, because those are async..but something like on_exchange_mtu_request handler isnt async so I cant await there to deal with something like BUSY response..

I think it's OK for now if the lib doesn't provide functions for the user to change data_length or att_mtu on demand. The current API where you request parameters on connect/advertise is good for the 99% of cases. Usually you just want to request highest MTU possible, and let the stack work it out, and then do whatever you can with the resulting negotiated MTU. If it's low then things will be slow, but you can't do much about it.

**Pull request merged**
