### PR TITLE
you wouldnt write a battery

### PR DESCRIPTION
**Pull request by jacobrosenthal**

### CODE REVIEW

**Comment by Dirbaio** [comment]
To charge my devices I write `100` to the battery level. Charges them faster than any charger in the market. Doesn't it work for you? There must be something wrong with your devices then...

**Comment by jacobrosenthal** [comment]
huh. never heard of it. I think its not permitted in the spec?

**Comment by jacobrosenthal** [comment]
I guess I dont care either way, but clicking 1.0 here for the spec for bas
https://www.bluetooth.com/specifications/gatt/
BAS_SPEC_V10.pdf

Battery Level
| Broadcast | Read | Write without Response | Write | Notify | Indicate | Signed Write | Reliable Write | Writable Auxiliaries |
|---|---|---|---|---|---|---|---|---|
| X | M | X | X | O | X | X | X | X |

Requirements marked with ‘M’ are mandatory, ‘O’ are optional and ‘X’ are excluded (not permitted).

**Comment by Dirbaio** [comment]
hahaha I was joking :joy: 

It was there just  to showcase the ability to write. Makes sense that it's forbidden by the spec.

It's definitely a good idea to make the examples adhere to the spec yup. Maybe we should find another standard service that has more complex writes etc and add another example.

**Comment by jacobrosenthal** [comment]
Listen. I would not be surprised to hear some insane manufacturer somewhere making it so writing to battery changed charging mode or something :)

Yeah I figured it was just having a complete set of stuff to test and see peripheral usage. I can clone the example and pick another one of the standards uuids that has read and write

**Pull request closed without merging**
